# WhatATheme
markdown: kramdown

# URL of the Site
url: www.hornsofplenty.co.uk
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Horns of Plenty
# Description of the Site
description: Oxford's community street band
# URL of Image of the Site
site-image: android-chrome-512x512.png
# Keywords of the Site
site-keywords: band, street band, community band, fanfare, oxford, horns, music, gigs, trumpet, saxaphone, clarinet, drums, trombone
# URL for the Image of custom Favicon
favicon-url: favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: /assets/images/red-splash.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info@hornsofplenty.com
facebook_username: hornsofplenty
twitter_username: horns_of_plenty
instagram_username:
youtube_channel_id: UC7SRMASfkyhstyLbuMlsT4Q
spotify_username:

# Google Analytics
google-analytics: # todo

# Disqus
disqus-shortname:

# Name of the Author
author-name: Horns of Plenty
# URL for the Image of the Author
author-image: https://github.com/HornsOfPlenty.png
# 60 Words About the Author
author-about: Horns of Plenty are Oxford's community street band
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.hornsofplenty.co.uk

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
